name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: crypto_password
          MYSQL_DATABASE: crypto_price_checker
          MYSQL_USER: crypto_user
          MYSQL_PASSWORD: crypto_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=crypto_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        run: docker-compose up -d --build

      - name: Copy .env
        run: docker exec app php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: docker exec app composer install --prefer-dist --no-progress --no-suggest

      - name: Generate Key
        run: docker exec app php artisan key:generate

      - name: Run Migrations
        run: docker exec app php artisan migrate --force

      - name: Set Directory Permissions
        run: docker exec app chmod -R 777 storage bootstrap/cache

      - name: Run PestPHP Tests
        run: docker exec app vendor/bin/pest --parallel
